/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Houdini.h
 #	source generated by 4D Plugin Wizard
 #	Project : Houdini
 #	author : miyako
 #	2023/08/31
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_HOUDINI_H
#define PLUGIN_HOUDINI_H

#include "4DPluginAPI.h"
#include "houdini/houdini.h"

#include "C_TEXT.h"
#include "C_BLOB.h"
#include "C_LONGINT.h"

#pragma mark -

void Houdini_Escape_XML(PA_PluginParameters params);
void Houdini_Unescape_HTML(PA_PluginParameters params);
void Houdini_Escape_HTML(PA_PluginParameters params);
void Houdini_Escape_URI(PA_PluginParameters params);
void Houdini_Escape_URL(PA_PluginParameters params);
void Houdini_Escape_HREF(PA_PluginParameters params);
void Houdini_Unescape_URI(PA_PluginParameters params);
void Houdini_Unescape_URL(PA_PluginParameters params);
void Houdini_Escape_JS(PA_PluginParameters params);
void Houdini_Unescape_JS(PA_PluginParameters params);

#endif /* PLUGIN_HOUDINI_H */
