/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Houdini
 #	author : miyako
 #	2016/04/16
 #
 # --------------------------------------------------------------------------------*/



// --- Houdini
void Houdini_Escape_XML(sLONG_PTR *pResult, PackagePtr pParams);
void Houdini_Unescape_HTML(sLONG_PTR *pResult, PackagePtr pParams);
void Houdini_Escape_HTML(sLONG_PTR *pResult, PackagePtr pParams);
void Houdini_Escape_URI(sLONG_PTR *pResult, PackagePtr pParams);
void Houdini_Escape_URL(sLONG_PTR *pResult, PackagePtr pParams);
void Houdini_Escape_HREF(sLONG_PTR *pResult, PackagePtr pParams);
void Houdini_Unescape_URI(sLONG_PTR *pResult, PackagePtr pParams);
void Houdini_Unescape_URL(sLONG_PTR *pResult, PackagePtr pParams);
void Houdini_Escape_JS(sLONG_PTR *pResult, PackagePtr pParams);
void Houdini_Unescape_JS(sLONG_PTR *pResult, PackagePtr pParams);
